#!/bin/bash

cp /etc/pihole/adlists.list /etc/pihole/regex.list /etc/pihole/setupVars.conf /etc/pihole/whitelist.txt /root/pihole-backup /root/pihole/ | tee -a /root/backup.log ; \
    sed -i -E s/^WEBPASSWORD=[A-Za-z0-9]*/WEBPASSWORD=/ /root/pihole/setupVars.conf | tee -a /root/backup.log; \
    sed -i -E s/.=[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}.[0-9]\{1,3\}/=/g /root/pihole/setupVars.conf | tee -a /root/backup.log ; \
    cd /root/pihole ; \
    git add . ; \
    git commit -m "$(date +"%m-%d-%Y")" ; \
    git push origin master
